name: CI pipeline

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.x"
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v7

  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.x"
      - name: Install go-ignore-cov
        run: go install github.com/quantumcycle/go-ignore-cov@latest
      - name: Run tests
        env:
          SECRET_KEY: not_secret
          DATABASE_URL: postgres://postgres:password@localhost:5432/test_db?sslmode=disable
        run: make cover
      - name: Get total coverage
        run: |
          go tool cover -func=cover.out | awk 'END { print "Total coverage: " $NF }' >> $GITHUB_STEP_SUMMARY
      - name: Upload coverage data
        uses: actions/upload-artifact@v4
        with:
          name: cover.out
          path: cover.out